CREATE TABLE NATION (  
ID int NOT NULL,  
NAME varchar(50) default NULL,  
VALUE varchar(3) default NULL,  
PRIMARY KEY  (ID)) 

INSERT INTO NATION(ID, NAME, VALUE) VALUES (1, 'ARGENTINA', 'ARG');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (2, 'BRASILE', 'BRA');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (3, 'CHILE', 'CHI');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (4, 'COLOMBIA', 'COL');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (5, 'FRANCIA', 'FRA');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (6, 'GEORGIA', 'GEO');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (7, 'GERMANIA', 'GER');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (8, 'GHANA', 'GHA');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (9, 'GRECIA', 'GRE');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (10, 'IRAN', 'IRN');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (11, 'ITALIA', 'ITA');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (12, 'MONTENEGRO', 'MON');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (13, 'NORVEGIA', 'NOR');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (14, 'OLANDA', 'OLA');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (15, 'PORTOGALLO', 'POR');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (16, 'REP. CECA', 'RCE');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (17, 'ROMANIA', 'ROM');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (18, 'SLOVENIA', 'SLO');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (19, 'SVEZIA', 'SVE');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (20, 'URUGUAY', 'URU');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (21, 'USA', 'USA');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (22, 'COSTA D''AVORIO', 'CDA');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (23, 'SVIZZERA', 'SVI');