CREATE TABLE NATION (  
ID int NOT NULL,  
NAME varchar(50) default NULL,  
VALUE varchar(3) default NULL,  
PRIMARY KEY  (ID)) 

INSERT INTO NATION(ID, NAME, VALUE) VALUES (1, 'ARGENTINA', 'ARG');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (2, 'BRASILE', 'BRA');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (3, 'CHILE', 'CHI');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (4, 'COLOMBIA', 'COL');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (5, 'FRANCIA', 'FRA');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (6, 'GEORGIA', 'GEO');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (7, 'GERMANIA', 'GER');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (8, 'GHANA', 'GHA');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (9, 'GRECIA', 'GRE');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (10, 'IRAN', 'IRN');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (11, 'ITALIA', 'ITA');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (12, 'MONTENEGRO', 'MON');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (13, 'NORVEGIA', 'NOR');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (14, 'OLANDA', 'OLA');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (15, 'PORTOGALLO', 'POR');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (16, 'REP. CECA', 'RCE');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (17, 'ROMANIA', 'ROM');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (18, 'SLOVENIA', 'SLO');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (19, 'SVEZIA', 'SVE');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (20, 'URUGUAY', 'URU');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (21, 'USA', 'USA');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (22, 'COSTA D''AVORIO', 'CDA');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (23, 'SVIZZERA', 'SVI');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (24, 'BELGIO', 'BEL');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (25, 'UNGHERIA', 'UNG');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (26, 'AUSTRIA', 'AUT');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (27, 'SERBIA', 'SRB');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (28, 'ALBANIA', 'ALB');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (29, 'CONGO', 'CON');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (30, 'MAROCCO', 'MAR');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (31, 'HONDURAS', 'HON');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (32, 'TUNISIA', 'TUN');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (33, 'ALGERIA', 'ALG');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (34, 'FINLANDIA', 'FIN');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (35, 'PERU', 'PER');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (36, 'POLONIA', 'POL');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (37, 'SLOVACCHIA', 'SLV');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (38, 'GUINEA', 'GUI');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (39, 'GIAPPONE', 'GIA');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (40, 'NIGERIA', 'NIG');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (41, 'PARAGUAY', 'PAR');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (42, 'LITUANIA', 'LIT');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (43, 'BOSNIA-ERZEG.', 'BOS');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (44, 'DANIMARCA', 'DAN');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (45, 'SPAGNA', 'SPA');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (46, 'SIERRA LEONE', 'SLE');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (47, 'MACEDONIA', 'MKD');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (48, 'ISRAELE', 'ISR');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (49, 'CAMERUN', 'CAM');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (50, 'SENEGAL', 'SEN');

CREATE TABLE POSITION (  
ID int NOT NULL,  
NAME varchar(50) default NULL,  
VALUE varchar(3) default NULL,  
PRIMARY KEY  (ID)) 

INSERT INTO POSITION(ID, NAME, VALUE) VALUES (1, 'Portiere', 'POR');
INSERT INTO POSITION(ID, NAME, VALUE) VALUES (2, 'Difensore', 'DIF');
INSERT INTO POSITION(ID, NAME, VALUE) VALUES (3, 'Centrocampista', 'CEN');
INSERT INTO POSITION(ID, NAME, VALUE) VALUES (4, 'Attaccante', 'ATT');

CREATE TABLE DIVISION (  
ID int NOT NULL,  
NAME varchar(50) default NULL,
VALUE varchar(5) default NULL,  
LEVEL int NOT NULL,
NATION_ID int NOT NULL,
PRIMARY KEY  (ID));

INSERT INTO DIVISION(ID, NAME, VALUE) VALUES (1, 'SERIE A', 'A', 1, 11);
INSERT INTO DIVISION(ID, NAME, VALUE) VALUES (2, 'SERIE B', 'B', 2, 11);
INSERT INTO DIVISION(ID, NAME, VALUE) VALUES (3, '1 DIVISIONE GIR. A', '1DIVA', 3, 11);
INSERT INTO DIVISION(ID, NAME, VALUE) VALUES (4, '1 DIVISIONE GIR. B', '1DIVB', 3, 11);
INSERT INTO DIVISION(ID, NAME, VALUE) VALUES (5, '2 DIVISIONE GIR. A', '2DIVA', 4, 11);
INSERT INTO DIVISION(ID, NAME, VALUE) VALUES (6, '2 DIVISIONE GIR. B', '2DIVB', 4, 11);
INSERT INTO DIVISION(ID, NAME, VALUE) VALUES (8, 'SERIE D', 'D', 5, 11);
INSERT INTO DIVISION(ID, NAME, VALUE) VALUES (9, 'ECCELLENZA', 'ECC', 6, 11);
INSERT INTO DIVISION(ID, NAME, VALUE) VALUES (10, 'PROMOZIONE', 'PROM', 7, 11);


INSERT INTO DIVISION(ID, NAME, VALUE) VALUES (11, 'PREMIER LEAGUE', 'PL', 1, 99);
INSERT INTO DIVISION(ID, NAME, VALUE) VALUES (12, 'FOOTBALL LEAGUE CHAMPIONSHIP', 'PL', 2, 99);
INSERT INTO DIVISION(ID, NAME, VALUE) VALUES (13, 'FOOTBALL LEAGUE ONE', 'PL', 3, 99);
INSERT INTO DIVISION(ID, NAME, VALUE) VALUES (14, 'FOOTBALL LEAGUE TWO', 'PL', 4, 99);

INSERT INTO DIVISION(ID, NAME, VALUE) VALUES (21, 'LEAGUE 1', 'L1', 1, 5);
INSERT INTO DIVISION(ID, NAME, VALUE) VALUES (22, 'LEAGUE 2', 'L2', 2, 5);
INSERT INTO DIVISION(ID, NAME, VALUE) VALUES (23, 'NATIONAL', 'NAT, 3, 5);

