CREATE TABLE NATION (  
ID int NOT NULL,  
NAME varchar(50) default NULL,  
VALUE varchar(3) default NULL,  
PRIMARY KEY  (ID)) 

INSERT INTO NATION(ID, NAME, VALUE) VALUES (1, 'ARGENTINA', 'ARG');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (2, 'BRASILE', 'BRA');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (3, 'CHILE', 'CHI');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (4, 'COLOMBIA', 'COL');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (5, 'FRANCIA', 'FRA');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (6, 'GEORGIA', 'GEO');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (7, 'GERMANIA', 'GER');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (8, 'GHANA', 'GHA');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (9, 'GRECIA', 'GRE');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (10, 'IRAN', 'IRN');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (11, 'ITALIA', 'ITA');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (12, 'MONTENEGRO', 'MON');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (13, 'NORVEGIA', 'NOR');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (14, 'OLANDA', 'OLA');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (15, 'PORTOGALLO', 'POR');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (16, 'REP. CECA', 'RCE');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (17, 'ROMANIA', 'ROM');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (18, 'SLOVENIA', 'SLO');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (19, 'SVEZIA', 'SVE');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (20, 'URUGUAY', 'URU');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (21, 'USA', 'USA');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (22, 'COSTA D''AVORIO', 'CDA');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (23, 'SVIZZERA', 'SVI');



CREATE TABLE CONTINENT (  
ID int NOT NULL,  
NAME varchar(50) default NULL,  
PRIMARY KEY  (ID))

INSERT INTO CONTINENT(ID, NAME) VALUES (1, 'EUROPA');
INSERT INTO CONTINENT(ID, NAME) VALUES (2, 'AFRICA');
INSERT INTO CONTINENT(ID, NAME) VALUES (3, 'NORD AMERICA');
INSERT INTO CONTINENT(ID, NAME) VALUES (4, 'CENTRO AMERICA');
INSERT INTO CONTINENT(ID, NAME) VALUES (5, 'SUD AMERICA');
INSERT INTO CONTINENT(ID, NAME) VALUES (6, 'ASIA');
INSERT INTO CONTINENT(ID, NAME) VALUES (7, 'AUSTRALIA');


ALTER TABLE NATION ADD COLUMN CONTINENT_ID int NOT NULL


UPDATE NATION SET CONTINENT_ID = 1 
WHERE NAME IN (
'ITALIA', 'GERMANIA', 'FRANCIA', 'INGHILTERRA', 'BELGIO', 'SLOVACCHIA', 'AUSTRIA', 'IRLANDA', 'BOSNIA-ERZEG.', 'UNGHERIA', 'UCRAINA', 'MACEDONIA',
'ISLANDA', 'DANIMARCA', 'SCOZIA', 'GALLES', 'OLANDA', 'SVEZIA', 'SPAGNA', 'ROMANIA', 'PORTOGALLO', 'POLONIA', 'FINLANDIA', 'KOSOVO',
'ALBANIA', 'CROAZIA', 'SLOVENIA', 'SERBIA', 'NORVEGIA', 'GRECIA', 'MONTENEGRO', 'BULGARIA', 'SVIZZERA', 'REP. CECA', 'RUSSIA', 'LITUANIA', 'TURCHIA'
);

UPDATE NATION SET CONTINENT_ID = 2 
WHERE NAME IN (
'ALGERIA', 'ANGOLA', 'CAMERUN', 'CONGO', 'COSTA D''AVORIO', 'EGITTO', 'GABON', 'GHANA', 'KENIA',
'MAROCCO', 'MOZAMBICO', 'NIGERIA', 'SENEGAL', 'TUNISIA', 'SIERRA LEONE', 'CAPO VERDE', 'GUINEA', 'GUINEA EQUATORIALE',
'MALI', '', '', '', '', '', '', '', ''
);

UPDATE NATION SET CONTINENT_ID = 3 
WHERE NAME IN (
'CANADA', 'USA', '', '', '', '', '', '', '',
'', '', '', '', '', '', '', '', ''
);


UPDATE NATION SET CONTINENT_ID = 4 
WHERE NAME IN (
'MESSICO', 'COSTARICA', 'HONDURAS', 'GUADALUPA', '', '', '', '', '',
'', '', '', '', '', '', '', '', ''
);

UPDATE NATION SET CONTINENT_ID = 5 
WHERE NAME IN (
'ARGENTINA', 'BRASILE', 'CILE', 'COLOMBIA', 'PARAGUAY', 'PERU', 'URUGUAY', 'SURINAME', '',
'', '', '', '', '', '', '', '', ''
);

UPDATE NATION SET CONTINENT_ID = 6 
WHERE NAME IN (
'AFGHANISTAN', 'ARABIA SAUDITA', 'CINA', 'GIAPPONE', 'IRAN', 'ISRAELE', 'GEORGIA', '', '',
'', '', '', '', '', '', '', '', ''
);

UPDATE NATION SET CONTINENT_ID = 7
WHERE NAME IN (
'AUSTRALIA', '', '', '', '', ''
);
