CREATE TABLE NATION (  
ID int NOT NULL,  
NAME varchar(50) default NULL,  
VALUE varchar(3) default NULL,  
PRIMARY KEY  (ID)) 

INSERT INTO NATION(ID, NAME, VALUE) VALUES (1, 'ARGENTINA', 'ARG');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (2, 'BRASILE', 'BRA');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (3, 'CHILE', 'CHI');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (4, 'COLOMBIA', 'COL');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (5, 'FRANCIA', 'FRA');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (6, 'GEORGIA', 'GEO');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (7, 'GERMANIA', 'GER');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (8, 'GHANA', 'GHA');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (9, 'GRECIA', 'GRE');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (10, 'IRAN', 'IRN');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (11, 'ITALIA', 'ITA');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (12, 'MONTENEGRO', 'MON');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (13, 'NORVEGIA', 'NOR');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (14, 'OLANDA', 'OLA');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (15, 'PORTOGALLO', 'POR');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (16, 'REP. CECA', 'RCE');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (17, 'ROMANIA', 'ROM');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (18, 'SLOVENIA', 'SLO');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (19, 'SVEZIA', 'SVE');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (20, 'URUGUAY', 'URU');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (21, 'USA', 'USA');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (22, 'COSTA D''AVORIO', 'CDA');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (23, 'SVIZZERA', 'SVI');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (24, 'BELGIO', 'BEL');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (25, 'UNGHERIA', 'UNG');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (26, 'AUSTRIA', 'AUT');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (27, 'SERBIA', 'SRB');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (28, 'ALBANIA', 'ALB');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (29, 'CONGO', 'CON');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (30, 'MAROCCO', 'MAR');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (31, 'HONDURAS', 'HON');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (32, 'TUNISIA', 'TUN');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (33, 'ALGERIA', 'ALG');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (34, 'FINLANDIA', 'FIN');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (35, 'PERU', 'PER');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (36, 'POLONIA', 'POL');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (37, 'SLOVACCHIA', 'SLV');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (38, 'GUINEA', 'GUI');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (39, 'GIAPPONE', 'GIA');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (40, 'NIGERIA', 'NIG');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (41, 'PARAGUAY', 'PAR');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (42, 'LITUANIA', 'LIT');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (43, 'BOSNIA-ERZEG.', 'BOS');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (44, 'DANIMARCA', 'DAN');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (45, 'SPAGNA', 'SPA');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (46, 'SIERRA LEONE', 'SLE');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (47, 'MACEDONIA', 'MKD');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (48, 'ISRAELE', 'ISR');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (49, 'CAMERUN', 'CAM');
INSERT INTO NATION(ID, NAME, VALUE) VALUES (50, 'SENEGAL', 'SEN');

CREATE TABLE POSITION (  
ID int NOT NULL,  
NAME varchar(50) default NULL,  
VALUE varchar(3) default NULL,  
PRIMARY KEY  (ID)) 

INSERT INTO POSITION(ID, NAME, VALUE) VALUES (1, 'Portiere', 'POR');
INSERT INTO POSITION(ID, NAME, VALUE) VALUES (2, 'Difensore', 'DIF');
INSERT INTO POSITION(ID, NAME, VALUE) VALUES (3, 'Centrocampista', 'CEN');
INSERT INTO POSITION(ID, NAME, VALUE) VALUES (4, 'Attaccante', 'ATT');

CREATE TABLE DIVISION (  
ID int NOT NULL,  
NAME varchar(50) default NULL,
VALUE varchar(5) default NULL,
LEVEL int NOT NULL,
NATION_ID int NOT NULL,  
PRIMARY KEY  (ID)) 

INSERT INTO DIVISION(ID, NAME, VALUE, TEAM_NUMBER, LEVEL, NATION_ID) VALUES ( -1, 'DILETTANTI', 'DIL', -1, -1);

INSERT INTO DIVISION(ID, NAME, VALUE, TEAM_NUMBER, LEVEL, NATION_ID) VALUES ( 1, 'SERIE A', 'A', 20, 1, 11);
INSERT INTO DIVISION(ID, NAME, VALUE, TEAM_NUMBER, LEVEL, NATION_ID) VALUES ( 2, 'SERIE B', 'B', 22, 2, 11);
INSERT INTO DIVISION(ID, NAME, VALUE, TEAM_NUMBER, LEVEL, NATION_ID) VALUES ( 3, '1 DIVISIONE A', '1DIVA', 3, 11);
INSERT INTO DIVISION(ID, NAME, VALUE, TEAM_NUMBER, LEVEL, NATION_ID) VALUES ( 4, '1 DIVISIONE B', '1DIVB', 3, 11);
INSERT INTO DIVISION(ID, NAME, VALUE, TEAM_NUMBER, LEVEL, NATION_ID) VALUES ( 5, '2 DIVISIONE A', '2DIVA', 4, 11);
INSERT INTO DIVISION(ID, NAME, VALUE, TEAM_NUMBER, LEVEL, NATION_ID) VALUES ( 6, '2 DIVISIONE B', '2DIVB', 4, 11);

INSERT INTO DIVISION(ID, NAME, VALUE, TEAM_NUMBER, LEVEL, NATION_ID) VALUES ( 7, 'PRIMERA DIVISION', 'SPD', 20, 1, 45);
INSERT INTO DIVISION(ID, NAME, VALUE, TEAM_NUMBER, LEVEL, NATION_ID) VALUES ( 8, 'SEGUNDA DIVISION', 'SSD', 22, 2, 45);

INSERT INTO DIVISION(ID, NAME, VALUE, TEAM_NUMBER, LEVEL, NATION_ID) VALUES ( 9, 'PREMIER LEAGUE', 'IPL', 20, 1, 13);
INSERT INTO DIVISION(ID, NAME, VALUE, TEAM_NUMBER, LEVEL, NATION_ID) VALUES (10, 'CHAMPIONSHIP', 'IPC', 24, 2, 13);

INSERT INTO DIVISION(ID, NAME, VALUE, TEAM_NUMBER, LEVEL, NATION_ID) VALUES (11, 'ERSTE BUNDESLIGA', 'GEB', 18, 1, 7);
INSERT INTO DIVISION(ID, NAME, VALUE, TEAM_NUMBER, LEVEL, NATION_ID) VALUES (12, 'ZWEITE BUNDESLIGA', 'GZB', 18, 2, 7);

INSERT INTO DIVISION(ID, NAME, VALUE, TEAM_NUMBER, LEVEL, NATION_ID) VALUES (13, 'PRIMEIRA LIGA', 'PLG', 16, 1, 15);
INSERT INTO DIVISION(ID, NAME, VALUE, TEAM_NUMBER, LEVEL, NATION_ID) VALUES (14, 'SEGUNDA DIVISION', 'PSD', 22, 2, 15);

INSERT INTO DIVISION(ID, NAME, VALUE, TEAM_NUMBER, LEVEL, NATION_ID) VALUES (15, 'LIGUE 1', 'FL1', 20, 1, 5);
INSERT INTO DIVISION(ID, NAME, VALUE, TEAM_NUMBER, LEVEL, NATION_ID) VALUES (16, 'LIGUE 2', 'FL2', 20, 2, 5);

INSERT INTO DIVISION(ID, NAME, VALUE, TEAM_NUMBER, LEVEL, NATION_ID) VALUES (17, 'PREM''ER-LIGA', 'RPL', 16, 1, 68);
INSERT INTO DIVISION(ID, NAME, VALUE, TEAM_NUMBER, LEVEL, NATION_ID) VALUES (18, 'PFN LIGI', 'RPL', 20, 2, 68);

INSERT INTO DIVISION(ID, NAME, VALUE, TEAM_NUMBER, LEVEL, NATION_ID) VALUES (19, 'EREDIVISIE', 'OED', 18, 1, 14);
INSERT INTO DIVISION(ID, NAME, VALUE, TEAM_NUMBER, LEVEL, NATION_ID) VALUES (20, 'EERSTTE DIVISIE', 'OEE', 20, 2, 14);

INSERT INTO DIVISION(ID, NAME, VALUE, TEAM_NUMBER, LEVEL, NATION_ID) VALUES (21, 'SOUPER LIGKA ELLADA', 'OED', 18, 1, 9);
INSERT INTO DIVISION(ID, NAME, VALUE, TEAM_NUMBER, LEVEL, NATION_ID) VALUES (22, 'FOOTBALL LEAGUE', 'OEE', 18, 2, 9);

INSERT INTO DIVISION(ID, NAME, VALUE, TEAM_NUMBER, LEVEL, NATION_ID) VALUES (23, 'PRO LEAGUE', 'BPL', 18, 1, 24);
INSERT INTO DIVISION(ID, NAME, VALUE, TEAM_NUMBER, LEVEL, NATION_ID) VALUES (24, 'TWEEDE KLASSE', 'BTK', 18, 2, 24);

INSERT INTO DIVISION(ID, NAME, VALUE, TEAM_NUMBER, LEVEL, NATION_ID) VALUES (25, 'PRIMERA DIVISION', 'APD', 20, 1, 1);
INSERT INTO DIVISION(ID, NAME, VALUE, TEAM_NUMBER, LEVEL, NATION_ID) VALUES (26, 'PRIMERA B NATIONAL', 'APN', 22, 2, 1);

INSERT INTO DIVISION(ID, NAME, VALUE, TEAM_NUMBER, LEVEL, NATION_ID) VALUES (27, 'SERIE A', 'BSA', 20, 1, 2);
INSERT INTO DIVISION(ID, NAME, VALUE, TEAM_NUMBER, LEVEL, NATION_ID) VALUES (28, 'SERIE B', 'BSB', 20, 2, 2);

INSERT INTO DIVISION(ID, NAME, VALUE, TEAM_NUMBER, LEVEL, NATION_ID) VALUES (29, 'EASTERN CONFERENCE', 'AEC', 10, 1, 21);
INSERT INTO DIVISION(ID, NAME, VALUE, TEAM_NUMBER, LEVEL, NATION_ID) VALUES (30, 'WESTERN CONFERENCE', 'AWC', 9, 2, 21);



CREATE TABLE CITY (  
ID int NOT NULL AUTO_INCREMENT,  
NAME varchar(50) default NULL,  
NATION_ID int NOT NULL,  
PRIMARY KEY  (ID));
